

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MesajlasmaUygulamasi.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DBBB1Entities : DbContext
{
    public DBBB1Entities()
        : base("name=DBBB1Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<gruplar> gruplar { get; set; }

    public virtual DbSet<mesajlar> mesajlar { get; set; }

    public virtual DbSet<uyeler> uyeler { get; set; }

}

}

