
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MesajlasmaUygulamasi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class mesajlar
{

    public int mesajId { get; set; }

    public string mesajMetni { get; set; }

    public System.DateTime mesajTarih { get; set; }

    public int mesajGrupId { get; set; }

    public int mesajUyeId { get; set; }



    public virtual gruplar gruplar { get; set; }

    public virtual uyeler uyeler { get; set; }

}

}
